-- Reference snapshot of the live Compass schema, generated by introspecting
-- the production Supabase project (npeegfsoijhdnnvuqjin) on 2026-08-06.
--
-- WHY THIS FILE EXISTS: every other file in supabase/ is an ALTER against a
-- base schema that was never itself committed — the base CREATE TABLEs for
-- cases, organisations, org_members, locations, employee_records,
-- hr_review_requests, profiles, and signing_requests only ever existed in
-- the live project (built via the dashboard/CLI without migration
-- tracking; `list_migrations` only goes back to 2026-08-04). That means the
-- schema could not be reproduced from this repo alone — no staging
-- environment, no way to safely test an RLS change before applying it live.
--
-- This file closes that gap for reference and disaster-recovery purposes.
-- IMPORTANT CAVEATS:
--   1. This is a best-effort snapshot generated via information_schema /
--      pg_catalog introspection, not a certified `pg_dump`. It's a reliable
--      reference, but treat it as documentation, not as something to blindly
--      replay — table order below is dependency-safe, but sequences,
--      extension versions, and some storage/auth-schema internals are not
--      captured.
--   2. For an authoritative, tool-generated baseline, run from a machine
--      with the Supabase CLI:
--        supabase link --project-ref npeegfsoijhdnnvuqjin
--        supabase db pull
--      That uses pg_dump against the real project and will produce a
--      migration Supabase's own tooling considers canonical — prefer it
--      over this file if the two ever disagree.
--   3. Do not run this file against the live project — the tables already
--      exist there. It's meant for spinning up a local/staging Postgres to
--      develop and test schema changes against before they go live.

-- ── Tables (dependency order) ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.organisations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  invite_code text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  notification_webhook_url text,
  notification_webhook_type text,
  plan text NOT NULL DEFAULT 'free'::text,
  stripe_customer_id text,
  stripe_subscription_id text,
  stripe_subscription_status text,
  CONSTRAINT organisations_pkey PRIMARY KEY (id),
  CONSTRAINT organisations_invite_code_key UNIQUE (invite_code),
  CONSTRAINT organisations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL,
  name text,
  role text DEFAULT 'hr_manager'::text,
  company text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
-- NOTE: unreferenced by any client or api/ code as of this snapshot — no
-- signup path currently writes to it (handle_new_user's trigger doesn't
-- exist in the live DB; see the function definition below). Kept here for
-- schema fidelity, but likely safe to drop along with handle_new_user()
-- after confirming nothing depends on it.

CREATE TABLE IF NOT EXISTS public.org_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid,
  user_id uuid,
  role text DEFAULT 'hr_manager'::text,
  name text,
  created_at timestamp with time zone DEFAULT now(),
  location_ids uuid[] DEFAULT '{}'::uuid[],
  is_hr boolean DEFAULT false,
  job_title text,
  access_level integer DEFAULT 5,
  email_digest_opt_in boolean NOT NULL DEFAULT true,
  CONSTRAINT org_members_pkey PRIMARY KEY (id),
  CONSTRAINT org_members_org_id_user_id_key UNIQUE (org_id, user_id),
  CONSTRAINT org_members_org_id_fkey FOREIGN KEY (org_id) REFERENCES organisations(id) ON DELETE CASCADE,
  CONSTRAINT org_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.org_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text,
  access_level integer,
  created_at timestamp with time zone,
  CONSTRAINT org_roles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid,
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT locations_pkey PRIMARY KEY (id),
  CONSTRAINT locations_org_id_fkey FOREIGN KEY (org_id) REFERENCES organisations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.employee_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  name text NOT NULL,
  job_title text,
  start_date text,
  location text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employee_records_pkey PRIMARY KEY (id),
  CONSTRAINT employee_records_org_id_name_key UNIQUE (org_id, name),
  CONSTRAINT employee_records_org_id_fkey FOREIGN KEY (org_id) REFERENCES organisations(id)
);

CREATE TABLE IF NOT EXISTS public.cases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  employee_name text NOT NULL,
  employee_email text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  org_id uuid,
  meetings jsonb DEFAULT '[]'::jsonb,
  vault_docs jsonb DEFAULT '[]'::jsonb,
  assigned_to uuid,
  created_by uuid,
  location_id uuid,
  hr_review_status text,
  hr_review_comments text,
  hr_reviewed_by uuid,
  hr_reviewed_at timestamp with time zone,
  evidence jsonb DEFAULT '[]'::jsonb,
  stage text DEFAULT 'open'::text,
  case_type text,
  description text,
  date_received text,
  urgency text,
  outcome text,
  investigation_report text,
  investigation_report_date text,
  disciplinary_officer text,
  disciplinary_officer_id text,
  disciplinary_officer_email text,
  investigating_manager text,
  handoff_date text,
  next_steps jsonb DEFAULT '[]'::jsonb,
  estimated_weekly_pay numeric,
  estimated_age_at_dismissal integer,
  confidential boolean NOT NULL DEFAULT false,
  CONSTRAINT cases_pkey PRIMARY KEY (id),
  CONSTRAINT cases_org_id_fkey FOREIGN KEY (org_id) REFERENCES organisations(id),
  CONSTRAINT cases_location_id_fkey FOREIGN KEY (location_id) REFERENCES locations(id),
  CONSTRAINT cases_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT cases_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT cases_hr_reviewed_by_fkey FOREIGN KEY (hr_reviewed_by) REFERENCES auth.users(id),
  CONSTRAINT cases_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE
);
-- NOTE: vault_docs is fetched by nothing in src/ or api/ (mapCaseRow drops
-- it) — dead column as of this snapshot. user_id/profiles is likewise
-- vestigial; org_id/created_by/assigned_to are what the app actually uses.

CREATE TABLE IF NOT EXISTS public.meetings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid,
  type text,
  date text,
  manager text,
  context text,
  transcript text,
  prep_pack text,
  structured_record text,
  risk_score jsonb,
  outcome_letter text,
  invite_letter text,
  appeal_letter text,
  participants jsonb,
  adjustments jsonb,
  saved_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meetings_pkey PRIMARY KEY (id),
  CONSTRAINT meetings_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE
);
-- NOTE: dead table as of this snapshot — the app stores meetings as a jsonb
-- array on cases.meetings instead (see src/lib/caseMapping.js) and nothing
-- in src/ or api/ queries this table. Likely an earlier normalized design
-- that was abandoned; src/db.js (deleted in this same cleanup pass) assumed
-- this table's shape, which is why it had drifted from the real schema.

CREATE TABLE IF NOT EXISTS public.case_access (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL,
  org_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'disciplinary_officer'::text,
  granted_by uuid,
  granted_at timestamp with time zone DEFAULT now(),
  CONSTRAINT case_access_pkey PRIMARY KEY (id),
  CONSTRAINT case_access_case_id_user_id_key UNIQUE (case_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.hr_review_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid,
  case_id uuid,
  meeting_id text,
  step text NOT NULL,
  requested_by uuid,
  requested_by_name text,
  requested_at timestamp with time zone DEFAULT now(),
  status text DEFAULT 'pending'::text,
  comments text,
  reviewed_by uuid,
  reviewed_by_name text,
  reviewed_at timestamp with time zone,
  case_employee_name text,
  meeting_type text,
  record_snapshot text,
  CONSTRAINT hr_review_requests_pkey PRIMARY KEY (id),
  CONSTRAINT hr_review_requests_org_id_fkey FOREIGN KEY (org_id) REFERENCES organisations(id) ON DELETE CASCADE,
  CONSTRAINT hr_review_requests_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE,
  CONSTRAINT hr_review_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id),
  CONSTRAINT hr_review_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.dsar_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  employee_name text NOT NULL,
  requested_by text,
  received_date date NOT NULL,
  due_date date NOT NULL,
  status text NOT NULL DEFAULT 'received'::text,
  completed_date date,
  notes text,
  reviewed_flagged_sections boolean NOT NULL DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  extended boolean NOT NULL DEFAULT false,
  extension_reason text,
  extended_at timestamp with time zone,
  CONSTRAINT dsar_requests_pkey PRIMARY KEY (id),
  CONSTRAINT dsar_requests_org_id_fkey FOREIGN KEY (org_id) REFERENCES organisations(id) ON DELETE CASCADE,
  CONSTRAINT dsar_requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.starter_instances (
  id text NOT NULL,
  org_id uuid NOT NULL,
  name text NOT NULL,
  role text,
  department text,
  manager text,
  email text,
  start_date text,
  template_id text,
  template_name text,
  tasks jsonb NOT NULL DEFAULT '[]'::jsonb,
  ai_customised boolean NOT NULL DEFAULT false,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT starter_instances_pkey PRIMARY KEY (id),
  CONSTRAINT starter_instances_org_id_fkey FOREIGN KEY (org_id) REFERENCES organisations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.leaver_instances (
  id text NOT NULL,
  org_id uuid NOT NULL,
  name text NOT NULL,
  role text,
  department text,
  manager text,
  email text,
  last_working_day text,
  reason text,
  template_id text,
  template_name text,
  tasks jsonb NOT NULL DEFAULT '[]'::jsonb,
  ai_customised boolean NOT NULL DEFAULT false,
  exit_interview_notes text,
  exit_interview_date text,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leaver_instances_pkey PRIMARY KEY (id),
  CONSTRAINT leaver_instances_org_id_fkey FOREIGN KEY (org_id) REFERENCES organisations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.employee_portal_invites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  employee_name text NOT NULL,
  email text NOT NULL,
  token text NOT NULL,
  created_by uuid,
  expires_at timestamp with time zone NOT NULL,
  accepted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_portal_invites_pkey PRIMARY KEY (id),
  CONSTRAINT employee_portal_invites_token_key UNIQUE (token),
  CONSTRAINT employee_portal_invites_org_id_fkey FOREIGN KEY (org_id) REFERENCES organisations(id) ON DELETE CASCADE,
  CONSTRAINT employee_portal_invites_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.employee_portal_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL,
  employee_name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  employee_email text,
  CONSTRAINT employee_portal_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT employee_portal_accounts_org_id_user_id_key UNIQUE (org_id, user_id),
  CONSTRAINT employee_portal_accounts_org_id_fkey FOREIGN KEY (org_id) REFERENCES organisations(id) ON DELETE CASCADE,
  CONSTRAINT employee_portal_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);
-- employee_email added 2026-08-06 (add_employee_email_to_portal_accounts)
-- so the portal API can disambiguate same-name employees instead of
-- matching by employee_name alone.

CREATE TABLE IF NOT EXISTS public.signing_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sign_id text NOT NULL,
  document text,
  employee_name text,
  manager_name text,
  meeting_type text,
  meeting_date text,
  status text DEFAULT 'pending'::text,
  signature text,
  signed_at text,
  created_at text,
  manager_email text,
  CONSTRAINT signing_requests_pkey PRIMARY KEY (id),
  CONSTRAINT signing_requests_sign_id_key UNIQUE (sign_id)
);
-- Intentionally has zero client-facing RLS policies (RLS is enabled with no
-- policies, so PostgREST denies anon/authenticated entirely) — the signer
-- isn't a logged-in Compass user, so api/signing.js is the only access path
-- and uses the service-role key. See that file's header comment.

CREATE TABLE IF NOT EXISTS public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL,
  user_name text NOT NULL,
  action text NOT NULL,
  detail text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_org_id_fkey FOREIGN KEY (org_id) REFERENCES organisations(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS audit_log_org_id_created_at_idx ON public.audit_log USING btree (org_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.api_rate_limits (
  rate_key text NOT NULL,
  window_start timestamp with time zone NOT NULL DEFAULT now(),
  request_count integer NOT NULL DEFAULT 0,
  CONSTRAINT api_rate_limits_pkey PRIMARY KEY (rate_key)
);
-- RLS enabled, no policies — client-facing access is fully denied; only
-- reachable via check_rate_limit()'s SECURITY DEFINER, by design.

CREATE TABLE IF NOT EXISTS public.calendar_connections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  org_id uuid NOT NULL,
  provider text NOT NULL,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT calendar_connections_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_connections_user_id_provider_key UNIQUE (user_id, provider),
  CONSTRAINT calendar_connections_provider_check CHECK (provider = 'google'::text),
  CONSTRAINT calendar_connections_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT calendar_connections_org_id_fkey FOREIGN KEY (org_id) REFERENCES organisations(id) ON DELETE CASCADE
);
-- RLS enabled, no policies — access_token/refresh_token only ever touched
-- server-side via service role (api/calendar/*).

CREATE TABLE IF NOT EXISTS public.calendar_synced_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  connection_id uuid NOT NULL,
  deadline_key text NOT NULL,
  calendar_event_id text NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT calendar_synced_events_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_synced_events_connection_id_deadline_key_key UNIQUE (connection_id, deadline_key),
  CONSTRAINT calendar_synced_events_connection_id_fkey FOREIGN KEY (connection_id) REFERENCES calendar_connections(id) ON DELETE CASCADE
);
-- RLS enabled, no policies — same reasoning as calendar_connections.

-- ── Row Level Security ─────────────────────────────────────────────────

ALTER TABLE public.organisations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.org_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.org_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.case_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hr_review_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dsar_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.starter_instances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaver_instances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_portal_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_portal_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signing_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_synced_events ENABLE ROW LEVEL SECURITY;

-- ── Helper functions (SECURITY DEFINER, used inside RLS policies) ──────

CREATE OR REPLACE FUNCTION public.my_org_ids()
 RETURNS SETOF uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select org_id from public.org_members where user_id = auth.uid()
$function$;

CREATE OR REPLACE FUNCTION public.org_has_members(p_org_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (select 1 from public.org_members where org_id = p_org_id)
$function$;

CREATE OR REPLACE FUNCTION public.can_access_case_location(p_org_id uuid, p_location_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  -- Members without a role-scoped location list (i.e. anyone who isn't a
  -- location_manager with locations assigned) see every location, matching
  -- current app behaviour where only location_manager is filtered client-side.
  SELECT NOT EXISTS (
    SELECT 1 FROM org_members om
    WHERE om.org_id = p_org_id
      AND om.user_id = auth.uid()
      AND om.role = 'location_manager'
      AND om.location_ids IS NOT NULL
      AND array_length(om.location_ids, 1) > 0
  )
  OR EXISTS (
    SELECT 1 FROM org_members om
    WHERE om.org_id = p_org_id
      AND om.user_id = auth.uid()
      AND p_location_id = ANY(om.location_ids)
  );
$function$;

CREATE OR REPLACE FUNCTION public.check_rate_limit(p_key text, p_limit integer, p_window_seconds integer)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_count int;
begin
  insert into public.api_rate_limits (rate_key, window_start, request_count)
  values (p_key, now(), 1)
  on conflict (rate_key) do update
    set request_count = case
          when public.api_rate_limits.window_start <= now() - make_interval(secs => p_window_seconds)
            then 1
          else public.api_rate_limits.request_count + 1
        end,
        window_start = case
          when public.api_rate_limits.window_start <= now() - make_interval(secs => p_window_seconds)
            then now()
          else public.api_rate_limits.window_start
        end
  returning request_count into v_count;

  return v_count <= p_limit;
end;
$function$;

CREATE OR REPLACE FUNCTION public.join_org_with_invite_code(p_invite_code text, p_name text)
 RETURNS TABLE(org_id uuid, org_name text, org_invite_code text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_org record;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if not check_rate_limit('join_org:' || auth.uid()::text, 10, 300) then
    raise exception 'Too many attempts — please wait a few minutes and try again.';
  end if;

  select id, name, invite_code into v_org
  from organisations
  where invite_code = upper(trim(p_invite_code));

  if v_org.id is null then
    raise exception 'Invalid invite code';
  end if;

  if exists (
    select 1 from org_members
    where org_members.org_id = v_org.id and org_members.user_id = auth.uid()
  ) then
    raise exception 'You are already a member of this organisation';
  end if;

  insert into org_members (org_id, user_id, role, name)
  values (v_org.id, auth.uid(), 'location_manager', trim(p_name));

  return query select v_org.id, v_org.name, v_org.invite_code;
end;
$function$;

-- Auth trigger function — no trigger currently wires it to auth.users in
-- the live DB (verified 2026-08-06: zero non-internal triggers on
-- auth.users besides FK constraint triggers), and nothing in src/ or api/
-- reads public.profiles. Kept for schema fidelity; EXECUTE is revoked from
-- anon/authenticated (2026-08-06 migration) since it isn't meant to be
-- called directly either way.
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into profiles (id, name, company)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', ''),
    coalesce(new.raw_user_meta_data->>'company', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$function$;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM public, anon, authenticated;

CREATE OR REPLACE FUNCTION public.protect_billing_columns()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if auth.role() <> 'service_role' then
    if new.plan is distinct from old.plan
      or new.stripe_customer_id is distinct from old.stripe_customer_id
      or new.stripe_subscription_id is distinct from old.stripe_subscription_id
      or new.stripe_subscription_status is distinct from old.stripe_subscription_status
    then
      raise exception 'Billing fields can only be changed by the billing system';
    end if;
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.protect_org_member_privilege_columns()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if (new.role is distinct from old.role) or (new.location_ids is distinct from old.location_ids) then
    if auth.role() <> 'service_role' and not exists (
      select 1 from public.org_members
      where org_id = old.org_id and user_id = auth.uid() and role in ('hr_director','hr_manager')
    ) then
      raise exception 'Only an HR Director or HR Manager can change a member''s role or location access';
    end if;
  end if;
  return new;
end;
$function$;

CREATE TRIGGER protect_billing_columns_trigger BEFORE UPDATE ON public.organisations
  FOR EACH ROW EXECUTE FUNCTION protect_billing_columns();

CREATE TRIGGER protect_org_member_privilege_columns_trigger BEFORE UPDATE ON public.org_members
  FOR EACH ROW EXECUTE FUNCTION protect_org_member_privilege_columns();

-- ── RLS policies ────────────────────────────────────────────────────────

CREATE POLICY organisations_insert_own ON public.organisations FOR INSERT
  WITH CHECK (created_by = auth.uid());
CREATE POLICY organisations_select_member_or_creator ON public.organisations FOR SELECT
  USING (id IN (SELECT my_org_ids()) OR created_by = auth.uid());
CREATE POLICY organisations_update_member ON public.organisations FOR UPDATE
  USING (id IN (SELECT my_org_ids())) WITH CHECK (id IN (SELECT my_org_ids()));

CREATE POLICY "Own profile" ON public.profiles FOR ALL
  USING (auth.uid() = id);

CREATE POLICY org_members_select_same_org ON public.org_members FOR SELECT
  USING (org_id IN (SELECT my_org_ids()));
CREATE POLICY org_members_update_same_org ON public.org_members FOR UPDATE
  USING (org_id IN (SELECT my_org_ids()));
CREATE POLICY org_members_insert_founding_member ON public.org_members FOR INSERT
  WITH CHECK (
    user_id = auth.uid() AND role = 'hr_director'
    AND NOT org_has_members(org_id)
    AND org_id IN (SELECT id FROM organisations WHERE created_by = auth.uid())
  );

CREATE POLICY org_roles_same_org ON public.org_roles FOR ALL
  USING (org_id IN (SELECT my_org_ids())) WITH CHECK (org_id IN (SELECT my_org_ids()));

CREATE POLICY locations_same_org ON public.locations FOR ALL
  USING (org_id IN (SELECT my_org_ids())) WITH CHECK (org_id IN (SELECT my_org_ids()));

CREATE POLICY "Users can manage employee records in their org" ON public.employee_records FOR ALL
  USING (org_id IN (SELECT my_org_ids()));

-- cases: two policies combine — the ALL policy (permissive) grants access,
-- the SELECT policy (restrictive) further narrows confidential rows. See
-- can_access_case_location() above for the location-scoping logic
-- (2026-08-06 fix — previously org-wide for every member regardless of role).
CREATE POLICY "Users can access cases in their org or assigned to them" ON public.cases FOR ALL
  USING (
    (org_id IN (SELECT my_org_ids()) AND can_access_case_location(org_id, location_id))
    OR id IN (SELECT case_id FROM case_access WHERE user_id = auth.uid())
  );
CREATE POLICY "Confidential cases restricted to authorised staff" ON public.cases AS RESTRICTIVE FOR SELECT
  USING (
    confidential = false
    OR created_by = auth.uid()
    OR EXISTS (SELECT 1 FROM case_access ca WHERE ca.case_id = cases.id AND ca.user_id = auth.uid())
    OR EXISTS (SELECT 1 FROM org_members om WHERE om.org_id = cases.org_id AND om.user_id = auth.uid() AND om.role = 'hr_director')
  );

CREATE POLICY "Own meetings" ON public.meetings FOR ALL
  USING (case_id IN (SELECT id FROM cases WHERE user_id = auth.uid()));
-- NOTE: this policy is effectively unreachable dead code — meetings is an
-- unused table (see its CREATE TABLE comment above) and cases.user_id is
-- itself vestigial (the app scopes by org_id/created_by, not user_id).

CREATE POLICY "Users can view case access in their org" ON public.case_access FOR SELECT
  USING (org_id IN (SELECT my_org_ids()));
CREATE POLICY "Users can grant case access in their org" ON public.case_access FOR INSERT
  WITH CHECK (org_id IN (SELECT my_org_ids()));
CREATE POLICY "Users can revoke case access in their org" ON public.case_access FOR DELETE
  USING (org_id IN (SELECT my_org_ids()));

CREATE POLICY hr_review_requests_same_org ON public.hr_review_requests FOR ALL
  USING (org_id IN (SELECT my_org_ids())) WITH CHECK (org_id IN (SELECT my_org_ids()));

CREATE POLICY dsar_requests_same_org ON public.dsar_requests FOR ALL
  USING (org_id IN (SELECT my_org_ids())) WITH CHECK (org_id IN (SELECT my_org_ids()));

CREATE POLICY "Users can manage starter instances in their org" ON public.starter_instances FOR ALL
  USING (org_id IN (SELECT my_org_ids()));
CREATE POLICY "Users can manage leaver instances in their org" ON public.leaver_instances FOR ALL
  USING (org_id IN (SELECT my_org_ids()));

CREATE POLICY audit_log_select_org_member ON public.audit_log FOR SELECT
  USING (org_id IN (SELECT my_org_ids()));
CREATE POLICY audit_log_insert_self ON public.audit_log FOR INSERT
  WITH CHECK (org_id IN (SELECT my_org_ids()) AND user_id = auth.uid());

-- employee_portal_invites, employee_portal_accounts, signing_requests,
-- api_rate_limits, calendar_connections, calendar_synced_events: RLS
-- enabled with zero policies (client-facing access fully denied by
-- default). All reads/writes go through api/portal/*, api/signing.js, and
-- api/calendar/* using the service-role key, which bypasses RLS entirely —
-- by design, not an oversight (see file-level comments on each table above
-- and api/signing.js's header comment).
