export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { to, subject, body, employeeName, meetingType, managerName, date } = req.body;

  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.RESEND_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from: 'Compass HR <onboarding@resend.dev>',
        to: [to],
        subject: subject || `${meetingType} Outcome Letter - ${employeeName}`,
        html: `
          <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px">
            <h2 style="color:#7C5CFC">Compass HR</h2>
            <p>Dear ${employeeName},</p>
            <p>Please find attached the outcome letter from your recent <strong>${meetingType}</strong> on <strong>${date}</strong>.</p>
            <div style="background:#f9f9f9;border-left:4px solid #7C5CFC;padding:16px;margin:20px 0;font-family:Georgia,serif;white-space:pre-wrap;font-size:14px;line-height:1.8">${body}</div>
            <p style="color:#666;font-size:12px">This letter was generated by Compass HR. If you have any questions please contact ${managerName}.</p>
          </div>
        `
      })
    });

    const data = await response.json();
    if (!response.ok) throw new Error(data.message || 'Failed to send');
    res.status(200).json({ success: true });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
}
