import { requireOrgMembership } from './_auth.js';
import { checkRateLimit } from './_rateLimit.js';
import { escapeHtml as esc } from './_html.js';

// Phase 6.5 hardening (P0) — previously verified only that SOME real
// Supabase session was calling (any authenticated identity on the whole
// project, including an employee portal account, not just this org's own
// staff), with no org-membership check and no rate limit, sending from
// Compass's own verified domain with a caller-controlled recipient/
// subject/body. requireOrgMembership closes the "any authenticated
// identity" gap; the rate limit caps abuse even from a legitimate but
// compromised account, the same pattern api/chat.js already uses.
export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { to, subject, body, orgId, employeeName, meetingType, managerName, date } = req.body;

  const auth = await requireOrgMembership(req, res, orgId);
  if (!auth) return;

  const withinLimit = await checkRateLimit(`send-letter:${auth.caller.id}`, 20, 300);
  if (!withinLimit) return res.status(429).json({ error: 'Too many requests — please wait a moment and try again.' });

  // Phase 6.5 hardening (Prompt 14, Section 7 — closes independent audit
  // finding 2.3, remaining half) — the P0 fix above closed "any
  // authenticated identity, not just this org's own staff"; this closes
  // "arbitrary recipient with zero validation at all". `to` staying
  // caller-chosen is deliberate — HR legitimately shares case
  // correspondence with external parties (solicitors, occupational
  // health, the employee's personal email) that Compass has no record
  // of, so this can't be restricted to a known-employee allow-list
  // without breaking that. What was genuinely missing is confirming `to`
  // is even a well-formed email address before Compass's own verified
  // sending domain relays arbitrary content to it.
  const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (typeof to !== 'string' || !EMAIL_RE.test(to)) {
    return res.status(400).json({ error: 'A valid recipient email address is required' });
  }

  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.RESEND_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from: 'Compass HR <notifications@mail.compasshruk.com>',
        to: [to],
        subject: subject || `${meetingType} Outcome Letter - ${employeeName}`,
        html: `
          <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px">
            <h2 style="color:#7C5CFC">Compass HR</h2>
            <p>Dear ${esc(employeeName)},</p>
            <p>Please find attached the outcome letter from your recent <strong>${esc(meetingType)}</strong> on <strong>${esc(date)}</strong>.</p>
            <div style="background:#f9f9f9;border-left:4px solid #7C5CFC;padding:16px;margin:20px 0;font-family:Georgia,serif;white-space:pre-wrap;font-size:14px;line-height:1.8">${esc(body)}</div>
            <p style="color:#666;font-size:12px">This letter was generated by Compass HR. If you have any questions please contact ${esc(managerName)}.</p>
          </div>
        `
      })
    });

    const data = await response.json();
    if (!response.ok) throw new Error(data.message || 'Failed to send');
    res.status(200).json({ success: true });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
}
